name: televerse
description: Televerse is a Telegram Bot API Framework written completely in Dart.
version: 1.0.0
homepage: https://github.com/HeySreelal/televerse

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
