name: televerse
description: Televerse is a Telegram Bot API Framework written completely in Dart. You can use this framework to create your own Telegram Bots, efficiently and easily.
version: 1.2.1
homepage: https://github.com/HeySreelal/televerse

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
