name: televerse
description: Televerse is a Telegram Bot API Framework written completely in Dart.
version: 0.0.1
homepage: https://github.com/HeySreelal/televerse

environment:
  sdk: ">=2.18.2 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
