name: televerse
description: Televerse lets you create your own efficient Telegram bots with ease in Dart. Supports latest Telegram Bot API - 6.9!
version: 1.11.1
homepage: https://github.com/HeySreelal/televerse

environment:
  sdk: ">=2.17.7 <4.0.0"

dependencies:
  dio: ^5.3.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  lints: ^2.0.0
  test: ^1.16.0
