name: televerse
description: Televerse lets you create your own efficient Telegram bots with ease in Dart. Supports latest Telegram Bot API - 6.9!
version: 1.11.5
homepage: https://github.com/HeySreelal/televerse

environment:
  sdk: ">=2.17.7 <4.0.0"

dependencies:
  dio: ^5.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
